# Generated by Django 5.1.1 on 2024-09-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='qrgenerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('descripcion', models.TextField()),
                ('vcard', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('wifi', models.TextField(blank=True, null=True)),
                ('geo', models.CharField(blank=True, max_length=100, null=True)),
                ('img_qr', models.ImageField(blank=True, null=True, upload_to='qrs/')),
            ],
        ),
    ]
